branches:
  only:
    - master
    - develop

matrix:
  include:
    - language: python
      python:
        - 3.6
        - 3.7
      install:
        - pip install -r requirements_dev.txt
      script:
        - black --check --verbose .
        - flake8
        - mypy .
        - coverage run --source=./eNMS -m pytest
      after_success:
        - coveralls

    - language: node_js
      node_js:
        - "node"
      script:
        - npm run prettier
        - npm run lint
